### ISSUE TITLE
Получить данные из Cian API

### ISSUE THREAD

**Issue by spelinichenko** [spelinichenko/TRKPO-Service#18]
Реализовать получение данных из Cian API согласно функциональной спецификации - Идентификатор: NF_Cian

**Comment by myway-it** [comment]
https://github.com/spelinichenko/TRKPO-Service/commit/e57b3ef22383546467ac2c5065a672589d6c0dc0
https://github.com/spelinichenko/TRKPO-Service/commit/2835e15e5b4d5c9353302e38d355a499d4844da4

Done
