### ISSUE TITLE
Разработать алгоритм по выявлению наиболее подходящих мест для открытия на основе данных osm

### ISSUE THREAD

**Issue by spelinichenko** [spelinichenko/TRKPO-Service#22]
Задача связана с пунктом из функциональной спецификации - Идентификатор: F_Response

**Comment by Nyakutka** [comment]
https://github.com/spelinichenko/TRKPO-Service/pull/11/commits/374a1d1773dad2b2d59d5fc83a1b68e6538dae2e

**Comment by Nyakutka** [comment]
1. Улица - находим Polygon в указанном районе, где меньше всего заведений с указанным типом кухни и типом заведения. В этом полигоне берем несколько объявлений циан 
2. Точный адрес помещения - берем из объявления циан в пункте 1
3. Площадь помещения (м2) - берем из объявления циан в пункте 1
4. Цена за помещение (руб/мес) - берем из объявления циан в пункте 1
5. Выгодное время работы (временной промежуток) - берем все заведения в районе (неважно какой тип, кухня) и смотрим самое раннее открытие N и самое позднее закрытие M. Возьмем для простоты выгодное время работы как [N-1ч, M+2ч].
6. Возможность доставки (по возможности доставки соседних заведений) - берем все заведения в районе (неважно какой тип, кухня). Если больше, чем 50% имеют доставку, то не будем рекомендовать ее. Если меньше или равно, то будем рекомендовать.
